project:
  type: website
  output-dir: docs

website:
  title: "Carina Grady"
  site-url: https://www.carinagrady.com/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: second-brain.qmd
        text: Second Brain
      - text: Portfolio
        menu:
          - href: portfolio-artistic.qmd
            text: Art
          - href: portfolio-engineering.qmd
            text: Engineering
      - href: contact.qmd
        text: Contact
format:
  html:
    theme: cosmo 
    toc: true  