project:
  type: website
  output-dir: docs

website:
  title: "Carina Grady"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: knowledge.qmd
        text: Knowledge
      - text: Portfolio
        menu:
          - href: portfolio-academic.qmd
            text: Academic
          - href: portfolio-work.qmd
            text: Work
          - href: portfolio-personal.qmd
            text: Personal
      - href: contact.qmd
        text: Contact
format:
  html:
    theme: cosmo 
    toc: true  